"""empty message

<<<<<<< HEAD:migrations/versions/41964a2bac18_.py
Revision ID: 41964a2bac18
Revises: 
Create Date: 2022-07-04 14:18:02.256967
=======
Revision ID: 403b98ba64c2
Revises: 
Create Date: 2022-07-04 10:37:43.640467
>>>>>>> 4882d51de4b1bd43fc2ca6812944a3de66d99225:migrations/versions/403b98ba64c2_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/41964a2bac18_.py
revision = '41964a2bac18'
=======
revision = '403b98ba64c2'
>>>>>>> 4882d51de4b1bd43fc2ca6812944a3de66d99225:migrations/versions/403b98ba64c2_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('autonomia', sa.String(length=80), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.String(length=360), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('ig_user', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('autonomia', sa.String(length=80), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.String(length=360), nullable=False),
    sa.Column('post1', sa.String(length=120), nullable=True),
    sa.Column('post2', sa.String(length=120), nullable=True),
    sa.Column('post3', sa.String(length=120), nullable=True),
    sa.Column('post4', sa.String(length=120), nullable=True),
    sa.Column('post5', sa.String(length=120), nullable=True),
    sa.Column('post6', sa.String(length=120), nullable=True),
    sa.Column('precio_post', sa.Integer(), nullable=True),
    sa.Column('precio_reel', sa.Integer(), nullable=True),
    sa.Column('precio_story', sa.Integer(), nullable=True),
    sa.Column('profilepic', sa.String(length=360), nullable=True),
    sa.Column('seguidores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ig_user')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('influencers')
    op.drop_table('empresas')
    # ### end Alembic commands ###
